// 한국어 문구(해요체). 랜딩·관리·로그인 흐름 화면 전부(§9.5·§8).
// 값의 원천은 docs/design/system/content.md §15.3이다(굵은 글자 그대로). 키는 중첩 객체이고 경로는 `.`로 잇는다(예 linkGone.title).
// 규칙: 요청은 ‘해 주세요’ 하나, 제목·라벨에는 마침표 없음, 본문에는 있음, 따옴표는 ‘ ’(content.md §3·§6).
// 허가 라벨 하나를 `allow`와 감사 기록 `audit.allow`(동작 이름으로 찾는 표)가 같이 쓴다(DC11: 같은 값의 키를 둘 두지 않는다)
const ALLOW_LABEL = "허가";

export const COPY = {
  siteName: "치지직 다운로더",
  // 랜딩 <title>·OG 제목. htmlPage가 이 값이면 " · 앱 이름" 꼬리를 붙이지 않는다
  siteTitle: "치지직 다운로더 — 비공식 다시보기·클립 다운로더",
  errorTitlePrefix: "오류: ",
  loginTitle: "치지직 다운로더 로그인",
  loginWarning: "치지직 다운로더 앱에서 직접 시작한 로그인이 아니면 이 창을 닫아 주세요. 다른 사람이 보낸 주소라면 계속하지 마세요. 로그인 뒤 주소창에 나오는 주소는 다른 사람에게 보내지 마세요.",
  loginContinue: "계속",
  // 안내·오류 페이지: 제목이 무슨 일인지, 본문이 다음에 할 일을 말한다(web.md §6.2). 같은 본문은 키 하나를 같이 쓴다
  linkGone: { title: "로그인 주소가 만료됐어요", body: "앱에서 다시 로그인해 주세요." },
  linkUsed: { title: "이미 사용한 로그인 주소예요" },
  badRequest: { title: "요청을 확인할 수 없어요", body: "페이지를 새로 연 뒤 다시 시도해 주세요." },
  rateLimited: { title: "요청이 너무 많아요" },
  busy: { title: "지금은 로그인 요청이 많아요" },
  retryLater: { body: "잠시 뒤 다시 시도해 주세요." },
  badFormat: { title: "요청 형식이 맞지 않아요" },
  adminOnly: { title: "관리자만 볼 수 있어요" },
  outdatedApp: { title: "앱을 업데이트해야 해요", body: "이 사이트 첫 화면에서 새 버전을 받아 설치해 주세요." },
  doneOk: { title: "로그인했어요" },
  doneDenied: {
    title: "이 채널은 사용 허가가 없어요",
    body: "관리자에게 채널 이름을 알려 주세요. 다른 계정으로 로그인하려면 네이버에서 먼저 로그아웃해 주세요.",
    next: "허가를 받은 뒤 다시 로그인해 주세요.",
  },
  doneCancelled: { title: "로그인을 취소했어요", body: "처음 화면에서 다시 로그인할 수 있어요." },
  // body = 앱 흐름(또는 흐름을 모를 때), webBody = 웹 흐름
  doneFailed: { title: "로그인하지 못했어요", body: "앱에서 다시 시도해 주세요.", webBody: "처음 화면에서 다시 로그인해 주세요." },
  channelLabel: "채널",
  channelIdLabel: "채널 ID",
  home: "처음으로",
  anonLead: "허가받은 채널만 쓸 수 있어요.",
  landing: {
  },
  loginWithChzzk: "치지직으로 로그인",
  anonAppHint: "앱을 이미 받았으면 앱 안에서 로그인해요.",
  signedInAs: (name: string): string => `‘${name}’ 채널로 로그인했어요.`,
  adminLink: "관리",
  downloadsTitle: "설치 파일",
  latestVersion: (v: string, d: string | null): string => (d === null ? `최신 버전 ${v}` : `최신 버전 ${v} · ${d}`),
  noRelease: "아직 올라온 버전이 없어요.",
  releaseUnavailable: "설치 파일 목록을 불러오지 못했어요. 잠시 뒤 다시 시도해 주세요.",
  colFile: "파일",
  artifact: {
    dmg: "macOS(Apple Silicon)",
    setup: "Windows 설치 프로그램(권장)",
    msi: "Windows MSI",
    appimage: "Linux AppImage",
    deb: "Linux deb(Debian·Ubuntu)",
  },
  appleSiliconOnly: "macOS는 Apple Silicon(M1 이후) Mac만 지원해요.",
  installHelp: "설치가 막힐 때",
  // macOS: 공증하지 않은 앱이라 처음 열 때 손상됐다는 경고가 나온다(W9 실기기 확인). 설정의 열기 버튼·우클릭 열기로는 풀리지 않아
  // 응용 프로그램으로 옮긴 뒤 격리 표시를 지우는 길만 안내한다. 앱 이름은 tauri.conf.json productName(worker-config.mjs checkLandingAppName)
  macDamaged: "처음 열 때 앱이 손상돼 열 수 없다는 경고가 나와도 휴지통으로 옮기지 마세요. Apple 공증을 받지 않은 앱이라 macOS가 막는 거예요. 앱이 문제라는 뜻이 아니에요. 아래 순서대로 해 주세요.",
  // 단계 세 개는 ol 항목이다(번호는 마크업이 붙인다)
  macMove: "받은 .dmg를 열고 앱을 ‘응용 프로그램’ 폴더로 옮겨 주세요.",
  macTerminal: "터미널을 열고 아래 명령을 붙여넣어 실행해 주세요.",
  macXattr: 'xattr -dr com.apple.quarantine "/Applications/치지직 다운로더.app"',
  macReopen: "응용 프로그램 폴더에서 앱을 다시 열어 주세요.",
  winSmartScreen: "Windows의 ‘PC 보호’ 창이 뜨면 ‘추가 정보’를 누른 뒤 ‘실행’을 눌러 주세요.",
  sameAccount: "앱을 연 뒤 이 페이지와 같은 치지직 계정으로 로그인해 주세요.",
  devicesTitle: "내 기기",
  devicesLead: "이 채널로 로그인한 앱과 브라우저예요. 모르는 기기가 있으면 끊어 주세요.",
  devicesEmpty: "로그인한 기기가 없어요.",
  // 시각은 한국 시간이다. 열 제목에는 시간대를 쓰지 않고 표 caption에 한 번 적는다
  tableTimeNote: "시각은 한국 시간이에요.",
  colKind: "종류",
  colClient: "기기 정보",
  colCreated: "로그인한 시각",
  colLastSeen: "마지막 확인",
  kindApp: "앱",
  kindWeb: "웹",
  thisBrowser: "이 브라우저",
  revoke: "끊기",
  logout: "로그아웃",
  adminsTitle: "관리자",
  adminsNote: "관리자는 서버 설정에서만 바꿀 수 있어요.",
  allowTitle: "허가한 채널",
  allowEmpty: "허가한 채널이 없어요.",
  colName: "이름",
  colNote: "메모",
  colAddedBy: "추가한 관리자",
  colAddedAt: "추가한 시각",
  colActive: "활성 로그인",
  disallow: "허가 빼기…",
  addTitle: "채널 ID로 추가",
  noteLabel: "메모(선택, 64자까지)",
  add: "추가",
  deniedTitle: "거부된 시도",
  deniedEmpty: "거부된 시도가 없어요.",
  colAttempts: "횟수",
  colFirstAt: "처음",
  colLastAt: "마지막",
  allow: ALLOW_LABEL,
  dismiss: "지우기",
  sessionsEmpty: "활성 로그인이 없어요.",
  colRecovered: "복구",
  auditTitle: "감사 기록",
  auditEmpty: "기록이 없어요.",
  colAt: "시각",
  colActor: "한 사람",
  colAction: "동작",
  colTarget: "대상",
  audit: {
    allow: ALLOW_LABEL,
    disallow: "허가 빼기",
    revoke_session: "로그인 끊기",
    reuse_detected: "재사용 감지",
    refresh_recovered: "로그인 복구",
    dismiss: "거부 기록 지우기",
  },
  bootstrapAdmin: { title: "아직 관리자가 정해지지 않았어요" },
  badBody: "요청을 읽지 못했어요.",
  badChannelId: "채널 ID는 영문 소문자와 숫자 32자리예요.",
  isAdmin: { title: "관리자 채널은 뺄 수 없어요" },
  adminNoAllow: { title: "관리자 채널은 허가 목록에 넣지 않아요", body: "관리자 설정에서만 정해요." },
  notFound: { title: "대상을 찾지 못했어요", body: "이미 처리됐을 수 있어요." },
} as const;
