// 한국어 문구(해요체). 랜딩·관리·로그인 흐름 화면 전부(§9.5·§8).
export const COPY = {
  siteName: "치지직 다운로더",
  loginTitle: "로그인 확인",
  loginLead: "앱 화면에 보이는 확인 코드와 같은지 확인해 주세요.",
  codeLabel: "확인 코드",
  loginWarning: "치지직 다운로더 앱에서 직접 시작한 로그인이 아니면 이 창을 닫으세요. 다른 사람이 보낸 링크라면 계속하지 마세요.",
  loginContinue: "계속",
  noticeTitle: "안내",
  linkGone: "이 로그인 링크는 만료됐거나 잘못됐어요. 앱에서 다시 로그인해 주세요.",
  linkUsed: "이미 사용한 로그인 링크예요. 앱에서 다시 로그인해 주세요.",
  badOrigin: "요청을 확인할 수 없어요. 페이지를 새로 연 뒤 다시 시도해 주세요.",
  rateLimited: "요청이 너무 잦아요. 잠시 뒤에 다시 시도해 주세요.",
  busy: "지금은 로그인 요청이 많아요. 잠시 뒤에 다시 시도해 주세요.",
  doneTitle: "로그인 결과",
  doneOkApp: "로그인했어요. 앱으로 돌아가세요.",
  doneOk: "로그인했어요.",
  doneDenied: "이 채널은 사용 허가가 없어요.",
  doneDeniedHint: "관리자에게 채널 이름을 알려 주세요.",
  doneDeniedSwitch: "다른 계정으로 로그인하려면 네이버에서 먼저 로그아웃해 주세요.",
  doneCancelled: "로그인을 취소했어요.",
  doneFailed: "로그인하지 못했어요. 앱에서 다시 시도해 주세요.",
  channelLabel: "채널",
  channelIdLabel: "채널 ID",
  home: "처음으로",
  landingTitle: "다운로드",
  anonLead: "허가된 채널만 받을 수 있어요.",
  loginWithChzzk: "치지직으로 로그인",
  anonAppHint: "앱을 이미 받았으면 앱 안에서 로그인해요.",
  signedInAs: (name: string): string => `${name} 채널로 로그인했어요.`,
  adminLink: "관리",
  downloadsTitle: "설치 파일",
  latestVersion: (v: string, d: string | null): string => (d === null ? `최신 버전 ${v}` : `최신 버전 ${v} · ${d}`),
  noRelease: "아직 올라온 버전이 없어요.",
  releaseUnavailable: "설치 파일 목록을 불러오지 못했어요. 잠시 뒤 다시 시도해 주세요.",
  colFile: "파일",
  artifact: {
    dmg: "macOS (Apple Silicon)",
    setup: "Windows 설치 프로그램(권장)",
    msi: "Windows MSI",
    appimage: "Linux AppImage",
    deb: "Linux deb(Debian·Ubuntu)",
  },
  appleSiliconOnly: "macOS는 Apple Silicon(M1 이후) Mac만 지원해요.",
  installHelp: "설치가 막힐 때",
  // macOS 15 문구와 아래 경로는 실기기에서 확인한다(W9)
  macGatekeeper: "처음 열 때 확인되지 않은 개발자라는 경고가 나오면 시스템 설정 → 개인정보 보호 및 보안 아래쪽의 [그래도 열기]를 눌러 주세요.",
  macTerminal: "터미널을 쓸 수 있으면 아래 명령으로 격리 표시를 지울 수 있어요.",
  macXattr: 'xattr -dr com.apple.quarantine "/Applications/치지직 다운로더.app"',
  winSmartScreen: "Windows의 PC 보호 창이 뜨면 [추가 정보] → [실행]을 눌러 주세요.",
  sameAccount: "앱을 연 뒤 이 페이지와 같은 치지직 계정으로 로그인해 주세요.",
  devicesTitle: "내 기기",
  devicesLead: "이 채널로 로그인한 앱과 브라우저예요. 모르는 기기가 있으면 끊어 주세요.",
  devicesEmpty: "로그인한 기기가 없어요.",
  colKind: "종류",
  colClient: "기기 정보",
  colCreated: "로그인한 시각(KST)",
  colLastSeen: "마지막 갱신(KST)",
  kindApp: "앱",
  kindWeb: "웹",
  thisBrowser: "이 브라우저",
  revoke: "끊기",
  logout: "로그아웃",
  adminTitle: "관리",
  adminsTitle: "관리자",
  adminsNote: "관리자는 Worker secret ADMIN_CHANNEL_IDS에서만 바꿀 수 있어요.",
  allowTitle: "허용 채널",
  allowEmpty: "허용된 채널이 없어요.",
  colName: "이름",
  colChannelId: "채널 ID",
  colNote: "메모",
  colAddedBy: "추가한 관리자",
  colAddedAt: "추가한 시각(KST)",
  colActive: "활성 세션",
  adminBadge: "관리자",
  disallow: "빼기",
  addTitle: "채널 ID로 추가",
  noteLabel: "메모(선택, 64자까지)",
  add: "추가",
  deniedTitle: "거부된 시도",
  deniedEmpty: "거부된 시도가 없어요.",
  colAttempts: "횟수",
  colFirstAt: "처음(KST)",
  colLastAt: "마지막(KST)",
  allow: "허용",
  dismiss: "지우기",
  sessionsTitle: "활성 세션",
  sessionsEmpty: "활성 세션이 없어요.",
  colChannel: "채널",
  colRecovered: "복구",
  auditTitle: "감사 기록",
  auditEmpty: "기록이 없어요.",
  colAt: "시각(KST)",
  colActor: "한 사람",
  colAction: "동작",
  colTarget: "대상",
  audit: {
    allow: "허용",
    disallow: "허용 빼기",
    revoke_session: "세션 끊기",
    reuse_detected: "재사용 감지",
    refresh_recovered: "갱신 복구",
    dismiss: "거부 기록 지우기",
  },
  bootstrapAdmin: "아직 관리자가 정해지지 않았어요.",
  notAdmin: "관리자만 볼 수 있어요.",
  badCsrf: "요청을 확인할 수 없어요. 페이지를 새로 연 뒤 다시 시도해 주세요.",
  unsupportedType: "요청 형식이 맞지 않아요.",
  badBody: "요청을 읽지 못했어요.",
  badChannelId: "채널 ID는 소문자 16진수 32자리예요.",
  isAdmin: "관리자 채널은 뺄 수 없어요.",
  adminNoAllow: "관리자 채널은 허용목록에 넣지 않아요. 관리자 설정에서만 정해요.",
  notFound: "대상을 찾지 못했어요. 이미 처리됐을 수 있어요.",
} as const;
