// 단계 (a)~(b) 동안 앱 tokens.css 끝에 두는 옛 토큰 이름 별칭(foundations 12-18, 계약 2.2).
// 옛 컴포넌트가 새 토큰 체계에서도 깨지지 않게 가장 가까운 새 sys 토큰으로 잇는다.
// 단계 (c)에서 옛 이름을 쓰는 곳이 없어지면 이 파일을 지운다(tokens.mjs의 legacy 절도 함께).
// 간격 --space-N(번호 → 값)은 별칭으로 풀 수 없어 소스에서 값 보존 이름으로 바꿨다.
export const LEGACY = [
  ['--accent-fg', 'var(--on-accent)'],
  ['--accent-hover', 'var(--accent-pressed)'],
  ['--border', 'var(--separator)'],
  ['--danger-fg', 'var(--on-accent)'],
  ['--danger-hover', 'var(--danger)'],
  ['--dur-fast', 'var(--motion-fast)'],
  ['--dur-base', 'var(--motion-base)'],
  ['--dur-slow', 'var(--motion-slow)'],
  ['--dur-highlight', '1000ms'],
  // --fg-disabled는 2.68:1이라 비활성이 아닌 힌트 글자에서 axe 대비 검사에 걸린다
  ['--fg-faint', 'var(--fg-muted)'],
  ['--focus-ring', '0 0 0 2px var(--surface), 0 0 0 4px var(--focus)'],
  ['--gutter', 'var(--space-16)'],
  ['--gutter-wide', 'var(--space-24)'],
  ['--header-h', 'var(--toolbar-h)'],
  ['--kind-clip', 'var(--fg)'],
  ['--kind-rewind', 'var(--fg)'],
  ['--kind-vod', 'var(--fg)'],
  ['--leading-tight', '1.3'],
  ['--leading-normal', '1.5'],
  ['--leading-relaxed', '1.65'],
  ['--radius-xs', 'var(--radius-badge)'],
  ['--radius-sm', 'var(--radius-control)'],
  ['--radius-md', 'var(--radius-control)'],
  ['--radius-lg', 'var(--radius-overlay)'],
  ['--radius-full', 'var(--radius-pill)'],
  ['--rail-w', '3px'],
  ['--success', 'var(--fg-muted)'],
  ['--surface-raised', 'var(--raised)'],
  ['--text-xs', 'var(--text-caption)'],
  ['--text-sm', 'var(--text-body)'],
  ['--text-md', 'var(--text-body)'],
  ['--text-lg', 'var(--text-title)'],
  ['--text-xl', 'var(--text-display)'],
  ['--tracking-tight', '0'],
  ['--warning', 'var(--warning-ink)'],
  ['--weight-normal', 'var(--weight-regular)'],
  ['--weight-medium', 'var(--weight-strong)'],
  ['--weight-semibold', 'var(--weight-strong)'],
  ['--z-banner', '30'],
];
