//! 프런트 TS 정의(`app/src/lib/bindings`) 생성.
//!
//! `#[ts(export)]`는 쓰지 않는다. 그것은 `cargo test`마다 파일을 고쳐 써서 "bindings가 최신인가" 검사를
//! 스스로 통과시켜 버린다. 대신 `export`가 정해진 설정(`u64` → `number`)으로 한 폴더에 모두 쓰고,
//! `tests/bindings.rs`가 임시 폴더에 만든 결과와 커밋된 폴더를 비교한다.
//! 다시 만들기: `UPDATE_BINDINGS=1 cargo test -p chzzk-shell --test bindings`.

use std::io;
use std::path::{Path, PathBuf};

use ts_rs::{Config, TS};

use crate::dto::{
    AppFolder, AppInfo, AuthStatusDto, CloseRequestedPayload, EnqueueRequest, JobDto, JobEvent,
    LegacyImportDto, OutputCheck, ResolvedDto, SettingsDto, SettingsPatch, UpdateCheckDto,
    UpdateInfoDto, UpdateInstallDto, UpdateProgressEvent,
};
use crate::error::AppError;

/// 생성 폴더(저장소 기준 `app/src/lib/bindings`).
pub fn default_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../app/src/lib/bindings")
}

/// 바인딩 생성 설정. 바이트·초·id는 2^53 미만이므로 `u64`를 `number`로 둔다(app.md §0).
pub fn config(dir: &Path) -> Config {
    Config::new().with_large_int("number").with_out_dir(dir)
}

/// 이름 순으로 정렬한 `index.ts`. `import type { X } from './bindings'`가 되게 한다.
pub const INDEX_FILE: &str = "index.ts";

fn ts_err(e: ts_rs::ExportError) -> io::Error {
    io::Error::other(e.to_string())
}

/// 프런트가 쓰는 모든 타입(과 그 의존 타입)의 TS 정의와 `index.ts`를 `dir`에 쓴다.
/// `dir`은 비어 있어야 한다(ts-rs는 같은 파일에 선언을 덧붙인다).
pub fn export(dir: &Path) -> io::Result<()> {
    std::fs::create_dir_all(dir)?;
    let cfg = config(dir);
    // command 인자·반환 타입. 의존 타입(JobId·ContentRef·…)은 함께 나간다.
    AppError::export_all(&cfg).map_err(ts_err)?;
    AppInfo::export_all(&cfg).map_err(ts_err)?;
    SettingsDto::export_all(&cfg).map_err(ts_err)?;
    SettingsPatch::export_all(&cfg).map_err(ts_err)?;
    LegacyImportDto::export_all(&cfg).map_err(ts_err)?;
    ResolvedDto::export_all(&cfg).map_err(ts_err)?;
    OutputCheck::export_all(&cfg).map_err(ts_err)?;
    EnqueueRequest::export_all(&cfg).map_err(ts_err)?;
    JobDto::export_all(&cfg).map_err(ts_err)?;
    JobEvent::export_all(&cfg).map_err(ts_err)?;
    AuthStatusDto::export_all(&cfg).map_err(ts_err)?;
    UpdateInfoDto::export_all(&cfg).map_err(ts_err)?;
    UpdateCheckDto::export_all(&cfg).map_err(ts_err)?;
    UpdateInstallDto::export_all(&cfg).map_err(ts_err)?;
    UpdateProgressEvent::export_all(&cfg).map_err(ts_err)?;
    CloseRequestedPayload::export_all(&cfg).map_err(ts_err)?;
    AppFolder::export_all(&cfg).map_err(ts_err)?;

    let mut names: Vec<String> = std::fs::read_dir(dir)?
        .filter_map(|e| e.ok())
        .filter_map(|e| e.file_name().into_string().ok())
        .filter(|n| n.ends_with(".ts") && n != INDEX_FILE)
        .map(|n| n.trim_end_matches(".ts").to_string())
        .collect();
    names.sort();
    let mut index = String::from(
        "// This file was generated by chzzk-shell `bindings::export`. Do not edit this file manually.\n\n",
    );
    for n in names {
        index.push_str(&format!("export type * from \"./{n}\";\n"));
    }
    std::fs::write(dir.join(INDEX_FILE), index)
}
