// copy deck(docs/design/system/content.md §2·§15.1). 화면 문구는 여기에만 둔다.
// 해요체. `{name}` 자리는 `t(key, { name })`가 채운다. 값은 content.md §15.1의 굵은 글자 그대로다(design-copy DC10이 비교한다).
// 같은 문구는 키 하나다(`common.*`). 숫자·날짜·크기는 `lib/format/`이 만들고 문구에는 변수만 둔다.
// 웹뷰 밖 문구(OS 알림 `crates/shell/src/notify.rs`, 시작 실패 창 `app/src-tauri/src/lib.rs`)는 Rust 상수이고, `tauri` gate가 이 값과 비교한다.

export const ko = {
  'app.title': 'VOD 클립 다운로더',
  'header.settings': '설정',
  'header.back': '뒤로',

  // 같은 문구 하나(content.md §2 키 이름)
  'common.close': '닫기',
  'common.cancel': '취소',
  'common.later': '나중에',
  'common.load': '불러오기',
  'common.showInList': '목록에서 보기',
  'common.openConfigFolder': '설정 폴더 열기',
  'common.keepUsing': '지금 버전은 계속 쓸 수 있어요.',

  // OS 분기(platform.md §20, design-copy DC9: OS별 글자는 이 `platform.*` 키에만). `lib/platform.ts`가 고른다
  'platform.mac.paste': '⌘V',
  'platform.other.paste': 'Ctrl+V',
  'platform.mac.submit': '⌘↩',
  'platform.other.submit': 'Ctrl+Enter',
  'platform.mac.reveal': 'Finder에서 보기',
  'platform.other.reveal': '폴더에서 보기',
  'platform.mac.devtools': '⌥⌘I',
  'platform.other.devtools': 'F12',
  // 웹 구성요소(엔진)가 오래됐을 때 고치는 법(platform.md §5): OS마다 방법이 달라 이 문구만 세 갈래다(`lib/platform.ts` `engineFixText`)
  'platform.mac.engineFix': 'macOS를 최신 버전으로 업데이트해 주세요.',
  'platform.windows.engineFix': 'Windows 업데이트에서 Microsoft Edge WebView2를 업데이트해 주세요.',
  'platform.linux.engineFix': '터미널에서 sudo apt upgrade를 실행해 주세요.',

  // 비공식 고지(content.md §11, design-copy DC6: Worker copy.ts와 바이트까지 같다)
  'notice.short': '비공식 도구예요 · 네이버·치지직과 제휴하거나 보증받지 않았어요',
  'notice.unofficial':
    'VOD 클립 다운로더는 네이버나 치지직과 관련 없는 비공식 도구예요. 치지직과 NAVER는 NAVER Corp.의 상표일 수 있어요. 이 앱은 로그인한 채널의 영상과 클립만 받아요.',

  'url.label': '영상 주소',
  'url.placeholder': '치지직 영상 주소',
  'url.dropHere': '여기에 놓으면 불러와요',
  'url.pasteHint': '{paste}로 붙여넣으면 바로 불러와요',
  'url.clipboard.title': '복사한 주소가 있어요',

  'recent.title': '최근 영상',
  'recent.reopen': '다시 열기',
  'recent.meta': '{kind} · {date}',

  'resolve.loading': '영상 정보를 불러오는 중',

  'card.title': '불러온 영상',
  'card.download': '받기',
  'card.added': '다운로드 목록에 넣었어요',

  'kind.liveRewind': '빠른 다시보기',
  'kind.vod': '일반 VOD',
  'kind.clip': '클립',
  'badge.adult': '19',
  'badge.adult.label': '연령 제한',

  'meta.liveDate': '{date} 방송',
  'meta.publishDate': '{date} 업로드',

  'quality.title': '화질',
  'quality.best': '가장 좋은 화질',

  'folder.change': '변경…',

  'filename.label': '파일 이름',
  'filename.reset': '원래 이름으로',
  'filename.willSaveAs': '저장될 이름: {name}',

  'conflict.exists': '같은 이름의 파일이 이미 있어요',
  'conflict.number': '번호를 붙여 받기',
  'conflict.overwrite': '덮어쓰기',
  'conflict.partial.title': '받다 만 파일이 있어요',
  'conflict.partial.body': '{size}까지 받았어요. 이어받으면 받던 곳부터 이어가요.',
  'conflict.partial.freshChosen': '받다 만 파일을 지우고 처음부터 받아요.',
  'conflict.partialOther': '다른 화질로 받다 만 파일이 있어요. 지우고 처음부터 받아요.',
  'conflict.inQueue': '이미 다운로드 목록에 있는 영상이에요',

  'list.title': '다운로드',
  'list.clearFinished': '완료 항목 지우기',
  'list.clearFinished.help': '목록에서만 지워요. 파일은 그대로 있어요.',
  'list.empty.title': '아직 받은 영상이 없어요',
  'list.empty.scope': '내 채널의 영상과 클립을 받을 수 있어요',
  'list.empty.step1': '치지직에서 영상 주소를 복사해 주세요',
  'list.empty.step2': '위 칸에 붙여넣어 주세요',
  'list.empty.step3': '화질을 고르고 받아 주세요',
  'list.cleared': '다운로드 목록이 비어 있어요',
  'list.group.running': '받는 중 {n}',
  'list.group.queued': '대기 중 {n}',
  'list.group.stopped': '받다 만 {n}',
  'list.group.finished': '완료 {n}',
  'power.keepingAwake': '받는 동안 잠들지 않아요',

  // 상태 어휘 두 층(content.md §3.1-2): 상태 줄은 명사형 조각(job.status.*), 사건 설명은 본문 줄(*.body)
  'job.queued': '대기 중 · 앞에 {n}개',
  'job.queuedNext': '대기 중 · 곧 시작',
  'job.status.queued': '대기 중',
  'job.status.resolving': '준비 중',
  'job.status.finalizing': '마무리 중',
  'job.status.paused': '일시정지됨',
  'job.status.completed': '완료',
  'job.status.skipped': '받지 않음',
  // 받는 중 상태 줄. 조각 결합도 deck이 한다(content.md §6.5). 총량을 모르면 NoTotal, 빠른 다시보기는 Segmented
  'job.running': '받는 중 · {received} / {total} · {speed} · {remaining}',
  'job.runningNoTotal': '받는 중 · {received} · {speed} · {remaining}',
  'job.runningSegmented': '받는 중 · {received} / {total} · 조각 {segDone}/{segTotal} · {speed} · {remaining}',
  'job.runningSegmentedNoTotal': '받는 중 · {received} · 조각 {segDone}/{segTotal} · {speed} · {remaining}',
  'job.completed': '완료 · {size} · {time}',
  'job.completedNoTime': '완료 · {size}',
  'job.completedMissing': '완료 · 파일 없음',
  'job.completedMissing.body': '파일을 옮기거나 지웠을 수 있어요.',
  'job.skipped.body': '같은 이름의 파일이 이미 있어요.',
  'job.skippedMeanwhile.body': '받는 동안 같은 이름의 파일이 생겼어요.',
  'job.phase.downloading': '받는 중',
  'job.phase.reresolving': '주소를 새로 받는 중',
  // 연결 대기(D40): 상태 머신이 아니라 running의 phase다. 오류가 아니므로 빨강·실패 문구가 없다. `{elapsed}`는 `formatElapsed`(`2분째`)
  'job.phase.waitingNetwork': '연결 대기 중',
  'job.status.waitingNetwork': '연결 대기 중 · {elapsed} · {received} 받음',
  'job.waitingNetwork.body': '인터넷이 돌아오면 이어서 받아요.',
  'job.recovered.body': '연결이 돌아와서 이어서 받고 있어요.',
  'job.stale.body': '{days}일 전에 멈췄어요. 디스크에 {size} 남아 있어요.',
  'job.pausing': '일시정지하는 중',
  'job.paused': '일시정지됨 · {bytes} 받음',
  'receive.admin.otherChannel.title': '다른 채널의 영상이에요',
  'receive.admin.otherChannel.body': '관리자라서 받을 수 있어요.',
  'receive.admin.unknown.title': '영상의 채널을 확인하지 못했어요',
  'receive.admin.unknown.body': '관리자라서 그대로 받을 수 있어요.',
  'job.otherChannel.body': '다른 채널로 로그인한 상태라 이어받을 수 없어요. 이 영상의 채널로 로그인해 주세요.',
  'job.resumedFrom': '{size}부터 이어받음',

  // 접근성 라벨 합성(content.md §10): 대상 먼저, 동작 뒤. 템플릿 안 합성 금지
  'a11y.progress': '{percent}퍼센트 받았어요. {remaining}',
  'a11y.more': '‘{title}’ 더 보기',
  'a11y.jobStatus': '‘{title}’: {status}',
  'a11y.cancelJob': '‘{title}’ 받기 취소',
  'a11y.reopen': '‘{title}’ 다시 열기',
  'a11y.resolved': '‘{title}’ 영상 정보를 불러왔어요',

  'action.pause': '일시정지',
  'action.resume': '이어받기',
  'action.retry': '다시 시도',
  'action.restartFresh': '처음부터 다시 받기',
  'action.undo': '되돌리기',
  'action.showTitle': '제목 전체 보기',
  'action.openFile': '열기',
  'action.remove': '목록에서 지우기',
  'action.copyUrl': '주소 복사',
  'action.copyReport': '문제 보고용 정보 복사',
  'action.reresolve': '다시 불러오기',
  'action.overwriteAndDownload': '덮어쓰고 받기…',
  'action.openCookieSettings': '네이버 로그인 정보 넣기…',
  'action.reenterCookies': '네이버 로그인 정보 다시 넣기…',
  'action.copied': '복사했어요',

  'toast.completed': '‘{title}’ 다운로드를 마쳤어요',
  'toast.removed': '목록에서 지웠어요',
  'toast.removedMany': '완료 항목 {n}개를 목록에서 지웠어요',
  'toast.signedIn': '‘{channelName}’ 채널로 로그인했어요',
  'toast.copyFailed': '복사하지 못했어요',
  'toast.reportHasPath': '복사한 정보에 파일 경로가 들어 있어요',

  'banner.interrupted': '지난번에 받다 만 영상이 {n}개 있어요.',
  'banner.resumeAll': '모두 이어받기',
  'banner.settingsError': '설정을 저장하지 못했어요. 디스크 공간과 권한을 확인해 주세요.',
  'engine.old.title': '이 컴퓨터의 웹 구성요소가 오래됐어요',
  'engine.old.body': '{fix} 앱은 그대로 쓸 수 있지만 화면 일부가 다르게 보일 수 있어요.',
  'banner.resumeNeedsLogin': '지난번에 받다 만 영상이 {n}개 있어요. 로그인하면 이어받을 수 있어요.',

  // 대화상자 7종(content.md §5.3 표가 유일한 원천). 안전 쪽 라벨은 현재 상태를 이어 가는 말이다
  'dialog.close.title': '받는 중인 영상을 일시정지하고 닫을까요?',
  'dialog.close.body': '받는 중인 영상이 {n}개 있어요. 닫으면 일시정지되고, 다음에 앱을 열면 이어받을 수 있어요.',
  'dialog.close.confirm': '일시정지하고 닫기',
  'dialog.cancel.title': '‘{title}’ 받기를 취소할까요?',
  'dialog.cancel.body': '{size}까지 받았어요. 취소하면 받다 만 파일이 지워지고 되돌릴 수 없어요.',
  'dialog.cancel.confirm': '취소하고 지우기',
  'dialog.cancel.keepRunning': '계속 받기',
  'dialog.cancel.keepPaused': '그대로 두기',
  'dialog.legacy.title': '예전 설정을 가져올까요?',
  'dialog.legacy.body': '예전 명령줄 버전에서 찾은 것이에요.',
  // 가져올 것의 항목이자 같은 글자를 쓰는 화면의 라벨(저장 폴더 필드, 쿠키 섹션 머리)이다: 같은 문구는 키 하나(content.md §2)
  'dialog.legacy.item.folder': '저장 폴더',
  'dialog.legacy.item.recent': '최근 영상 {n}개',
  'dialog.legacy.item.cookies': '네이버 로그인 정보',
  'dialog.legacy.import': '가져오기',
  'dialog.overwrite.title': '‘{name}’ 파일을 덮어쓸까요?',
  'dialog.overwrite.body': '지금 있는 파일을 지우고 새로 받아요. 되돌릴 수 없어요.',
  'dialog.overwrite.confirm': '덮어쓰고 받기',
  'dialog.logout.title': '로그아웃할까요?',
  'dialog.logout.body': '받는 중인 영상은 계속 받아요. 다시 쓰려면 치지직으로 다시 로그인해야 해요.',
  'dialog.logout.confirm': '로그아웃',
  'dialog.logout.keep': '로그인 유지',
  'dialog.update.title': '업데이트하고 다시 시작할까요?',
  'dialog.update.body': '받는 중인 영상 {n}개는 일시정지돼요. 다시 시작한 뒤 [이어받기]로 이어받을 수 있어요.',
  'dialog.update.confirm': '업데이트하고 다시 시작',

  'legacy.done': '설정을 가져왔어요',
  'legacy.notFound': '이 폴더에서 예전 설정을 찾지 못했어요',

  'settings.storage': '저장 위치',
  'settings.defaultFolder': '기본 저장 폴더',
  'settings.parallel': '동시에 받는 영상 수',
  'settings.parallel.help': '둘 이상이면 빨라질 수 있지만 인터넷을 더 많이 써요.',
  'settings.segments': '한 번에 받는 조각 수',
  'settings.segments.help':
    '빠른 다시보기는 영상을 작은 조각으로 나눠 받아요. 숫자가 클수록 빠르지만 인터넷을 더 많이 써요.',
  'settings.autoResume': '앱을 열면 받다 만 영상을 자동으로 이어받기',
  'settings.autoResume.help': '꺼져 있으면 위쪽 안내 줄에서 직접 이어받아요.',
  'settings.keepAwake': '받는 동안 컴퓨터가 잠들지 않게 하기',
  'settings.keepAwake.help': '끄면 한동안 자리를 비울 때 받기가 멈출 수 있어요. 화면은 꺼져도 돼요.',
  'settings.view': '보기',
  'settings.textScale': '글자 크기',
  'settings.textScale.default': '기본',
  'settings.textScale.large': '크게',
  'settings.textScale.xLarge': '아주 크게',
  'settings.theme': '모양',
  'settings.theme.system': '시스템',
  'settings.theme.light': '밝게',
  'settings.theme.dark': '어둡게',
  'settings.account': '계정',
  'settings.advanced': '고급',

  'settings.cookie.body':
    '연령 제한이나 구독자 전용 영상은 네이버에 로그인한 상태여야 받을 수 있어요. 브라우저에서 복사한 네이버 로그인 쿠키 두 개를 넣으면 이 컴퓨터의 설정 폴더에만 저장하고, 치지직 영상 정보를 불러올 때만 써요.',
  'settings.cookie.help':
    '이 값은 비밀번호 없이 로그인된 상태 그 자체예요. 개발자나 관리자는 이 값을 묻지 않아요. 보내 달라는 메시지를 받으면 사기예요. 네이버에서 로그아웃하면 값이 만료돼 다시 넣어야 해요.',
  'settings.cookie.use': '네이버 로그인 정보 사용',
  'settings.cookie.saved': '저장됨',
  'settings.cookie.notSaved': '저장된 값 없음',
  'settings.cookie.save': '저장',
  'settings.cookie.clear': '값 지우기',
  'settings.cookie.howto': '값을 찾는 방법',
  'settings.cookie.bothRequired': '두 값을 모두 넣어 주세요',
  'settings.cookie.show': '값 보기',
  'settings.cookie.howto.step1': '브라우저에서 chzzk.naver.com에 로그인해 주세요',
  'settings.cookie.howto.step2': '개발자 도구를 열어 주세요: {devtools}',
  'settings.cookie.howto.step3': '‘애플리케이션(Application)’ › ‘쿠키’에서 https://chzzk.naver.com 항목을 열어 주세요',
  'settings.cookie.howto.step4': '{cookieA}와 {cookieB}의 값을 각각 복사해 붙여넣어 주세요',

  'settings.legacy.title': '이전 버전',
  'settings.legacy.body': '예전 명령줄 버전의 설정과 최근 영상을 가져와요.',
  'settings.legacy.pick': '폴더 고르기…',
  'settings.legacy.last': '마지막 가져오기: {path}',

  'settings.about.title': '정보',
  'settings.about.version': '버전 {app}',
  'settings.about.licenses': '오픈소스 라이선스',
  'settings.about.openLogs': '로그 폴더 열기',
  'settings.about.checkUpdate': '업데이트 확인',
  'settings.about.checking': '업데이트 확인 중',
  'settings.about.upToDate': '최신 버전이에요',
  'settings.about.checkFailed': '업데이트를 확인하지 못했어요',
  'settings.about.checkOffline': '로그인 서버에 연결할 수 없어 확인하지 못했어요.',

  'auth.signedOut.title': '로그인이 필요해요',
  'auth.consent':
    '로그인하면 채널 이름과 채널 ID만 알게 되고, 네이버 비밀번호는 받지 않아요. 언제든 설정 › 계정에서 로그아웃할 수 있어요.',
  'auth.privacy': '개인정보 처리방침',
  'auth.intro': '허가받은 채널만 쓸 수 있어요. 치지직 계정으로 로그인해 주세요.',
  'auth.login': '치지직으로 로그인',
  'auth.relogin': '다시 로그인',
  'auth.relogin.help': '다시 로그인해 주세요.',
  'auth.reconnect': '다시 연결',
  'auth.reconnectFailed': '아직 연결되지 않았어요. 잠시 뒤 다시 연결해 주세요.',
  'auth.checking': '로그인 상태 확인 중',
  'auth.checking.body': '최대 {secs}초쯤 걸려요.',
  'auth.pending.title': '브라우저에서 로그인해 주세요',
  'auth.pending.body': '브라우저에서 치지직 로그인을 마치면 자동으로 넘어가요.',
  'auth.pending.remaining': '남은 시간 {mmss}',
  'auth.pending.sameDevice': '로그인 주소는 이 컴퓨터의 브라우저에서 열어 주세요.',
  'auth.pending.stuck': '브라우저에 연결할 수 없다는 오류가 보이면 다시 로그인해 주세요.',
  'auth.reopen': '브라우저 다시 열기',
  'auth.copyLoginUrl': '로그인 주소 복사',
  'auth.browserHelp': '브라우저가 열리지 않을 때',
  'auth.otherAccount': '다른 계정으로 로그인',
  'auth.otherAccount.help': '다른 계정으로 로그인하려면 브라우저에서 네이버 로그아웃을 먼저 해 주세요.',
  'auth.channelLabel': '로그인한 채널',
  'auth.denied.title': '사용 허가가 없는 채널이에요',
  'auth.denied.body': '허가를 받으려면 관리자에게 채널 이름을 알려 주세요. 허가를 받은 뒤 [다시 시도]를 눌러 주세요.',
  'auth.removed.title': '사용 허가가 더 이상 없어요',
  'auth.removed.body': '계속 쓰려면 관리자에게 문의해 주세요.',
  'auth.loginTimeout.title': '로그인 시간이 지났어요',
  'auth.loginTimeout.body': '로그인은 {mins}분 안에 마쳐야 해요. 다시 로그인해 주세요.',
  'auth.sessionExpired.title': '로그인이 만료됐어요',
  'auth.revoked.title': '다시 로그인이 필요해요',
  'auth.revoked.body': '이 기기의 로그인이 더 이상 유효하지 않아요. 다시 로그인해 주세요.',
  'auth.reuse.body': '보안을 위해 다시 로그인해 주세요.',
  'auth.graceExpired.title': '로그인 서버에 한동안 연결하지 못했어요',
  'auth.graceExpired.body': '인터넷 연결을 확인한 뒤 다시 연결해 주세요. 받는 중인 영상은 계속 받아요.',
  'auth.cancelled.title': '로그인을 취소했어요',
  'auth.network.title': '로그인 서버에 연결하지 못했어요',
  'auth.network.body': '인터넷 연결을 확인한 뒤 다시 시도해 주세요.',
  'auth.server.title': '로그인 요청을 처리하지 못했어요',
  'auth.server.body': '잠시 뒤 다시 시도해 주세요.',
  'auth.unknown.title': '로그인 상태를 확인하지 못했어요',
  'auth.unknown.body': '잠시 뒤 다시 로그인해 주세요.',
  'auth.lost.title': '로그인을 마무리하지 못했어요',
  'auth.receiver.title': '로그인을 준비하지 못했어요',
  'auth.receiver.body': '앱이 로그인 결과를 받을 준비를 하지 못했어요. 다시 로그인해 주세요.',
  'auth.runningNote':
    '받는 중이거나 대기 중인 영상 {n}개는 계속 받아요. 일시정지하려면 앱을 닫아 주세요. 다음에 로그인하면 이어받을 수 있어요.',

  'account.menu': '계정 메뉴',
  'account.scope': '허가받은 채널이에요',
  'account.lastSeen': '마지막 확인 {time}',
  'account.offline': '오프라인 · {until}까지 사용 가능',
  'account.offline.help': '로그인 서버에 연결하지 못했어요. 다시 연결되면 자동으로 확인해요.',
  'account.logout': '로그아웃…',

  'update.banner': '새 버전이 있어요: {version}',
  'update.install': '지금 업데이트',
  'update.downloading': '업데이트 받는 중 · {percent}',
  'update.installing': '설치하고 다시 시작하는 중',
  'update.failed': '업데이트하지 못했어요',
  'update.untrusted': '업데이트 파일을 확인할 수 없어 받지 않았어요',

  // OS 알림·전원 사유(content.md §14). Rust 상수(`crates/shell/src/notify.rs`)와 같은 글자다. 제목에 앱 이름을 넣지 않는다.
  // `notify.many`는 완료·실패 묶음 알림 둘의 본문 `many_body`다(제목은 `completed`·`failed`가 다르다)
  'notify.completed': '다운로드를 마쳤어요',
  'notify.failed': '다운로드를 마치지 못했어요',
  'notify.stalled': '받기가 멈췄어요',
  'notify.many': '{title} 외 {n}개',
  'power.reason': '치지직 영상 {n}개 받는 중',
} as const;

export type CopyKey = keyof typeof ko;
export type CopyVars = Record<string, string | number>;

/** 문구를 꺼내 `{name}` 자리를 채운다. 값이 없는 자리는 그대로 둔다(빠진 값이 눈에 띄게). */
export function t(key: CopyKey, vars?: CopyVars): string {
  const s: string = ko[key];
  if (!vars) return s;
  return s.replace(/\{(\w+)\}/g, (whole, name: string) =>
    name in vars ? String(vars[name]) : whole,
  );
}
