// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCode } from "./ErrorCode";
import type { ErrorPayload } from "./ErrorPayload";
import type { Stage } from "./Stage";

/**
 * 프런트로 가는 오류 하나. 모든 command의 `Err` 타입이다.
 */
export type AppError = { 
/**
 * UI 분기 키
 */
code: ErrorCode, 
/**
 * 코어 `Error`의 Display(셸 오류는 셸 문구). 문제 보고용
 */
message: string, 
/**
 * 작업 오류에만. 어느 단계에서 실패했는가
 */
stage: Stage | null, 
/**
 * `Error::is_resumable()`. `.part`가 실제로 남았는지는 `JobDto.partialBytes`로 본다
 */
resumable: boolean, payload: ErrorPayload | null, };
