// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `open_app_folder`가 여는 폴더(S2 저장·정보 섹션). 프런트에 opener 권한이 없어 Rust가 연다.
 */
export type AppFolder = "config" | "logs" | "downloads";
