// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Features } from "./Features";
import type { LegacyCandidate } from "./LegacyCandidate";

/**
 * `app_info` 결과.
 */
export type AppInfo = { version: string, coreVersion: string, configDir: string, dataDir: string, logDir: string, defaultDownloadFolder: string, features: Features, 
/**
 * 첫 실행에 옛 설정을 찾았을 때 한 번(D3)
 */
legacyCandidate: LegacyCandidate | null, };
