// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Features } from "./Features";
import type { LegacyCandidate } from "./LegacyCandidate";
import type { Os } from "./Os";
import type { TextScale } from "./TextScale";
import type { Theme } from "./Theme";

/**
 * `app_info` 결과.
 */
export type AppInfo = { version: string, coreVersion: string, configDir: string, dataDir: string, logDir: string, defaultDownloadFolder: string, features: Features, 
/**
 * 앱이 도는 OS(Windows 고정 데이터·단축키 표기·[Finder에서 보기] 분기)
 */
platform: Os, 
/**
 * 저장된 글자 크기. `get_settings`는 로그인 뒤에만 부를 수 있어 로그인 화면도 따르도록 여기에도 싣는다
 */
textScale: TextScale, 
/**
 * 저장된 모양(위와 같은 이유)
 */
theme: Theme, 
/**
 * 첫 실행에 옛 설정을 찾았을 때 한 번(D3)
 */
legacyCandidate: LegacyCandidate | null, };
