// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthState } from "./AuthState";

/**
 * `auth_status` 결과. Phase 2는 늘 `{state: "disabled"}`.
 */
export type AuthStatusDto = { state: AuthState, channelId: string | null, channelName: string | null, };
