// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthReason } from "./AuthReason";
import type { AuthState } from "./AuthState";
import type { OfflineDto } from "./OfflineDto";
import type { PendingDto } from "./PendingDto";

/**
 * `auth_status` 결과이자 `auth-changed` 이벤트 본문. 시각은 모두 유닉스 초(`JobDto.createdAt`과 같다).
 * 비밀(토큰·pollSecret·로그인 주소)은 없다.
 */
export type AuthStatusDto = { state: AuthState, channelId: string | null, channelName: string | null, reason: AuthReason | null, pending: PendingDto | null, offline: OfflineDto | null, verifiedAt: number | null, };
