// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 사유(worker.md §11.4의 10개). TS 이름은 `AuthReason`.
 */
export type AuthReason = "loginTimeout" | "sessionExpired" | "revoked" | "removedFromAllowlist" | "reuseDetected" | "graceExpired" | "network" | "server" | "loginLost" | "receiver";
