// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 로그인 상태.
 */
export type AuthState = "disabled" | "signedOut" | "pending" | "signedIn" | "denied" | "expired" | "cancelled" | "error";
