// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 로그인 상태. `Checking`은 A2에서 더했다(저장 세션을 서버로 확인하는 중).
 */
export type AuthState = "disabled" | "checking" | "signedOut" | "pending" | "signedIn" | "denied" | "expired" | "cancelled" | "error";
