// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `close-requested` 이벤트(§4). Rust가 창 닫기·앱 종료를 막았을 때 받는 중인 작업 수와 함께 보낸다(D1).
 */
export type CloseRequestedPayload = { running: number, };
