// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `chzzk_core::ContentRef`의 TS 모양.
 */
export type ContentRef = { "kind": "video", videoNo: number, } | { "kind": "clip", clipId: string, };
