// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentKind } from "./ContentKind";

/**
 * `ContentMeta` 미러.
 */
export type ContentMetaDto = { kind: ContentKind, title: string, channelName: string, channelId: string | null, 
/**
 * `"YYYY-MM-DD HH:MM:SS"`(KST)
 */
liveOpenDate: string | null, publishDate: string | null, adult: boolean, durationSecs: number | null, };
