// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 컨텐츠 종류. 코어 `ContentKind`는 `"Video"`로 직렬화되므로 §5대로 `"video"`가 되게 셸이 옮긴다.
 */
export type ContentKind = "video" | "clip";
