// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 웹뷰 엔진 기능 검사(platform §5, `frontend_ready`의 인자). 하나라도 false면 프런트가 경고 배너를 띄운다.
 * 키 이름은 CSS 기능 이름을 따른다.
 */
export type EngineProbe = { colorMix: boolean, has: boolean, oklch: boolean, containerQuery: boolean, inert: boolean, };
