// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentRef } from "./ContentRef";
import type { OnExisting } from "./OnExisting";
import type { PlaybackKind } from "./PlaybackKind";

/**
 * `enqueue` 인자.
 */
export type EnqueueRequest = { url: string, content: ContentRef, title: string, channelName: string, 
/**
 * 웹뷰가 아는 컨텐츠 채널 ID. 로그인을 쓰는 빌드에서 셸은 이 값을 믿지 않고 검증한 값으로 덮어쓴다(worker.md 구현 중 변경 82)
 */
channelId: string | null, qualityId: string, qualityLabel: string, expectedKind: PlaybackKind, folder: string | null, fileName: string, 
/**
 * UI는 `overwrite`만 보낸다
 */
onExisting: OnExisting, 
/**
 * true면 첫 시작 전에 `discard_partial(output)`
 */
restart: boolean, 
/**
 * 방송·공개 날짜(`meta.liveOpenDate ?? meta.publishDate`). 최근 영상 둘째 줄에만 쓴다. 없어도 된다
 */
contentDate?: string, };
