// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentRef } from "./ContentRef";
import type { OnExisting } from "./OnExisting";
import type { PlaybackKind } from "./PlaybackKind";

/**
 * `enqueue` 인자.
 */
export type EnqueueRequest = { url: string, content: ContentRef, title: string, channelName: string, 
/**
 * Phase 3 소유 재검사용
 */
channelId: string | null, qualityId: string, qualityLabel: string, expectedKind: PlaybackKind, folder: string | null, fileName: string, 
/**
 * UI는 `overwrite`만 보낸다
 */
onExisting: OnExisting, 
/**
 * true면 첫 시작 전에 `discard_partial(output)`
 */
restart: boolean, };
