// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobId } from "./JobId";
import type { PlaybackKind } from "./PlaybackKind";
import type { RequestKind } from "./RequestKind";

/**
 * 오류 문구에 끼워 넣을 값. 없는 종류가 대부분이다.
 */
export type ErrorPayload = { "type": "api", code: number, apiMessage: string | null, } | { "type": "http", status: number, requestKind: RequestKind, } | { "type": "authRequired", status: number, } | { "type": "noPlayback", adult: boolean, } | { "type": "qualityNotFound", requested: string, available: Array<string>, } | { "type": "playbackChanged", was: PlaybackKind, now: PlaybackKind, } | { "type": "path", path: string, } | { "type": "duplicateOutput", jobId: JobId, };
