// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 오류 종류. 앞 20개는 `chzzk_core::ErrorKind`와 1:1, 뒤는 셸 전용이다.
 */
export type ErrorCode = "invalidUrl" | "api" | "http" | "authRequired" | "noPlayback" | "encrypted" | "noQualities" | "qualityNotFound" | "playbackChanged" | "sourceChanged" | "refreshExhausted" | "unsupported" | "parse" | "lengthMismatch" | "network" | "diskFull" | "fileLocked" | "io" | "settings" | "cancelled" | "jobNotFound" | "duplicateOutput" | "invalidInput" | "fileMissing" | "notLoggedIn" | "notOwnContent" | "ownershipUnknown" | "internal";
