// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 기능 플래그. 프런트는 이 값으로만 분기한다.
 */
export type Features = { 
/**
 * Phase 3 로그인. Phase 2는 false
 */
auth: boolean, };
