// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 기능 플래그. 프런트는 이 값으로만 분기한다.
 */
export type Features = { 
/**
 * 로그인(Worker 주소가 있는 빌드). 릴리스는 늘 true(build.rs가 주소 없이는 막는다)
 */
auth: boolean, };
