// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";
import type { ContentKind } from "./ContentKind";
import type { JobId } from "./JobId";
import type { JobStatus } from "./JobStatus";
import type { PlaybackKind } from "./PlaybackKind";
import type { ProgressDto } from "./ProgressDto";

/**
 * 작업 하나.
 */
export type JobDto = { id: JobId, url: string, title: string, channelName: string, 
/**
 * 작업의 컨텐츠 채널 ID(없으면 null). 로그인을 쓰는 빌드는 셸이 검증한 값, 쓰지 않는 빌드는 요청 값이다. 막힌 작업 안내에 쓴다
 */
channelId: string | null, kind: ContentKind, playbackKind: PlaybackKind, qualityLabel: string, output: string, status: JobStatus, 
/**
 * 마지막 진행률(running·pausing·paused에서 표시)
 */
progress: ProgressDto | null, 
/**
 * failed
 */
error: AppError | null, 
/**
 * 작업이 멈춘 뒤 `.part`를 실제로 확인한 값(sidecar `committed_len`)
 */
partialBytes: number | null, 
/**
 * completed
 */
finalBytes: number | null, 
/**
 * completed인데 파일이 없다(reconcile)
 */
missing: boolean, 
/**
 * unix 초
 */
createdAt: number, finishedAt: number | null, 
/**
 * paused·interrupted·failed로 바뀐 시각(unix 초). 그 밖 상태와 옛 레코드는 null.
 * "멈춘 지 30일" 판단에 쓴다(`finishedAt`은 완료·건너뜀 전용이라 따로 둔다)
 */
stoppedAt: number | null, };
