// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";
import type { ContentKind } from "./ContentKind";
import type { JobId } from "./JobId";
import type { JobStatus } from "./JobStatus";
import type { PlaybackKind } from "./PlaybackKind";
import type { ProgressDto } from "./ProgressDto";

/**
 * 작업 하나.
 */
export type JobDto = { id: JobId, url: string, title: string, channelName: string, kind: ContentKind, playbackKind: PlaybackKind, qualityLabel: string, output: string, status: JobStatus, 
/**
 * 마지막 진행률(running·pausing·paused에서 표시)
 */
progress: ProgressDto | null, 
/**
 * failed
 */
error: AppError | null, 
/**
 * 작업이 멈춘 뒤 `.part`를 실제로 확인한 값(sidecar `committed_len`)
 */
partialBytes: number | null, 
/**
 * completed
 */
finalBytes: number | null, 
/**
 * completed인데 파일이 없다(reconcile)
 */
missing: boolean, 
/**
 * unix 초
 */
createdAt: number, finishedAt: number | null, };
