// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobDto } from "./JobDto";
import type { JobId } from "./JobId";
import type { ProgressDto } from "./ProgressDto";

/**
 * `subscribe_jobs` Channel로 가는 이벤트. 모두 작업 id를 품는다.
 */
export type JobEvent = { "type": "added", job: JobDto, } | { "type": "status", job: JobDto, } | { "type": "progress", id: JobId, progress: ProgressDto, } | { "type": "removed", id: JobId, };
