// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 작업 id. `jobs.json`의 `nextId`로 단조 증가한다. JSON·TS에서는 숫자다(2^53 미만 전제).
 * serde newtype이라 JSON에서는 감싸지 않은 숫자다.
 */
export type JobId = number;
