// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 작업 상태(§6.3).
 */
export type JobStatus = "queued" | "running" | "pausing" | "paused" | "interrupted" | "completed" | "skipped" | "failed";
