// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `keep-awake` 이벤트: 잠자기 방지를 **실제로 얻었을 때만** `active: true`(platform §10).
 */
export type KeepAwakePayload = { active: boolean, };
