// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `import_legacy` 적용 결과. 쿠키 값은 없다.
 */
export type LegacyImportDto = { recentCount: number, hasCookies: boolean, warnings: Array<string>, };
