// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 첫 실행에 찾은 옛 설정 폴더(적용 전).
 */
export type LegacyCandidate = { dir: string, recentCount: number, hasCookies: boolean, };
