// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 오프라인 유예(SignedIn일 때만)
 */
export type OfflineDto = { since: number, graceUntil: number, };
