// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 앱이 도는 OS(system/platform.md §20). 프런트는 `navigator`를 읽지 않고 이 값으로 분기한다(design-lint DX5).
 */
export type Os = "macos" | "windows" | "linux";
