// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobId } from "./JobId";
import type { PartialInfo } from "./PartialInfo";

/**
 * `check_output` 결과(§6.4).
 */
export type OutputCheck = { 
/**
 * sanitize + 200바이트 절단 후(확장자 제외)
 */
fileName: string, 
/**
 * 최종 경로
 */
path: string, 
/**
 * 입력과 `file_name`이 다르다
 */
truncated: boolean, 
/**
 * 완성 파일이 있다
 */
exists: boolean, 
/**
 * `exists`일 때 비어 있는 이름("이름 (2)")
 */
freeFileName: string | null, 
/**
 * `.part`가 있다
 */
partial: PartialInfo | null, 
/**
 * 같은 경로의 활성 작업
 */
duplicateJobId: JobId | null, };
