// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 본인 영상 판정(Phase 3). Phase 2는 늘 `unchecked`.
 */
export type Ownership = "unchecked" | "own" | "notOwn" | "unknown";
