// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 본인 영상 판정. 로그인을 쓰지 않는 빌드와 로그인 전은 `unchecked`.
 */
export type Ownership = "unchecked" | "own" | "notOwn" | "unknown";
