// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 받다 만 `.part` 정보.
 */
export type PartialInfo = { 
/**
 * sidecar `committed_len`(없거나 깨졌으면 `.part` 길이)
 */
bytes: number, 
/**
 * 같은 컨텐츠·화질·방식의 `.part`다
 */
sameJob: boolean, };
