// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 로그인 대기(확인 코드와 로컬 기한)
 */
export type PendingDto = { userCode: string, expiresAt: number, };
