// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Phase } from "./Phase";

/**
 * 코어 `Progress`를 평평하게 편 것(튜플은 JSON 배열이 되므로).
 */
export type ProgressDto = { phase: Phase, bytes: number, totalBytes: number | null, totalBytesEstimate: number | null, segmentsDone: number | null, segmentsTotal: number | null, mediaSecsDone: number | null, mediaSecsTotal: number | null, speedBps: number | null, etaSecs: number | null, resumedFrom: number, refreshes: number, };
