// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `Quality` 미러.
 */
export type QualityDto = { 
/**
 * 선택 키(정확 일치)
 */
id: string, 
/**
 * 표시·"마지막 화질" 기억용
 */
label: string, resolution: number | null, width: number | null, height: number | null, bandwidth: number | null, frameRate: string | null, };
