// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecentKind } from "./RecentKind";

/**
 * 최근 VOD 한 항목.
 */
export type RecentVodDto = { url: string, title: string, 
/**
 * 종류(옛 항목은 없다)
 */
kind: RecentKind | null, 
/**
 * 방송·공개 날짜(API 문자열 그대로, 프런트 format이 읽는다). 옛 항목은 없다
 */
date: string | null, };
