// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `chzzk_core::RecentKind`의 TS 모양(프런트 배지 `vod`·`rewind`·`clip`과 같은 이름).
 */
export type RecentKind = "vod" | "rewind" | "clip";
