// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 요청 종류(코어 `RequestKind`는 직렬화되지 않아 셸이 미러를 둔다).
 */
export type RequestKind = "api" | "mpd" | "media";
