// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentMetaDto } from "./ContentMetaDto";
import type { ContentRef } from "./ContentRef";
import type { Ownership } from "./Ownership";
import type { PlaybackKind } from "./PlaybackKind";
import type { QualityDto } from "./QualityDto";

/**
 * `resolve` 결과. 서명 URL은 없다.
 */
export type ResolvedDto = { 
/**
 * 정규화된 입력 주소
 */
url: string, content: ContentRef, meta: ContentMetaDto, playbackKind: PlaybackKind, 
/**
 * 원래 순서
 */
qualities: Array<QualityDto>, 
/**
 * `Resolved::default_quality(last_quality_label)`
 */
defaultQualityIndex: number, 
/**
 * `default_filename`에서 `.mp4`를 뗀 것
 */
suggestedFileName: string, ownership: Ownership, };
