// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecentVodDto } from "./RecentVodDto";

/**
 * `UserSettings` 미러. 쿠키 값은 없다(`naverCookiesSaved`만).
 */
export type SettingsDto = { downloadFolder: string | null, 
/**
 * `download_folder`가 없으면 기본 폴더
 */
effectiveDownloadFolder: string, useNaverCookies: boolean, naverCookiesSaved: boolean, lastQualityLabel: string | null, lastUrl: string | null, recentVods: Array<RecentVodDto>, segmentConcurrency: number, 
/**
 * 동시 다운로드 수(1~3, 기본 2). §16
 */
maxParallelDownloads: number, 
/**
 * 재시작 후 멈춘 작업을 자동으로 이어받는다(기본 꺼짐). §16
 */
autoResumeInterrupted: boolean, importedFrom: string | null, };
