// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TextScale } from "./TextScale";
import type { Theme } from "./Theme";

/**
 * `update_settings` 인자. 없는 키는 바꾸지 않는다.
 */
export type SettingsPatch = { 
/**
 * 키 없음 = 그대로, `null` = 기본 폴더로, 문자열 = 그 폴더로
 */
downloadFolder?: string | null, useNaverCookies?: boolean, 
/**
 * 1~8로 자른다
 */
segmentConcurrency?: number, 
/**
 * 1~3으로 자른다
 */
maxParallelDownloads?: number, autoResumeInterrupted?: boolean, textScale?: TextScale, 
/**
 * 다른 OS에서도 받아 저장한다(화면이 Linux에서만 보낸다)
 */
theme?: Theme, };
