// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `chzzk_core::TextScale`의 TS 모양(값 = `data-text-scale`, `default`는 속성 없음).
 */
export type TextScale = "default" | "large" | "x-large";
