// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 업데이트 정보(`update-available` 본문, `update_check`·`update_available` 결과). 시각은 유닉스 초.
 * 다운로드 주소는 담지 않는다.
 */
export type UpdateInfoDto = { version: string, current: string, notes: string | null, pubDate: number | null, };
