// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateInfoDto } from "./UpdateInfoDto";

/**
 * `update_check` 결과. `offline`은 "세션 판정이 유효하지 않음(오프라인 유예·로그인 아님·refresh 실패)"이다.
 */
export type UpdateCheckDto = { "result": "available", info: UpdateInfoDto, } | { "result": "upToDate" } | { "result": "offline" } | { "result": "failed" } | { "result": "untrusted" };
