// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `update_install` 결과
 */
export type UpdateInstallDto = { "result": "needsConfirm", running: number, } | { "result": "upToDate" } | { "result": "offline" } | { "result": "failed" } | { "result": "untrusted" } | { "result": "busy" } | { "result": "restarting" };
