// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `update-progress` 이벤트 본문. `Chunk`는 누적 `received`이고 정수 퍼센트가 오를 때만 보낸다.
 */
export type UpdateProgressEvent = { "type": "started", total: number | null, } | { "type": "chunk", received: number, total: number | null, } | { "type": "downloaded" } | { "type": "installing" };
