// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `open_web_page`가 여는 Worker 페이지(로그인 서버 주소 아래 고정 경로, system/patterns.md §13·§14.4).
 */
export type WebPage = "privacy" | "licenses";
