// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `window-focus` 이벤트: main 창이 포커스를 얻거나 잃을 때(system/platform.md §3 비활성 창, foundations §10).
 * 프런트는 macOS에서만 `html[data-window-active]`에 옮긴다.
 */
export type WindowFocusPayload = { focused: boolean, };
